"""
schemas.py — Pydantic v2 request / response models.

Keeps API contracts separate from database models.
"""

import base64
import re
from datetime import datetime
from pydantic import BaseModel, EmailStr, Field, ConfigDict, field_validator

USERNAME_RE = re.compile(r"^[a-zA-Z0-9_.-]{3,64}$")


# ===========================================================================
# User schemas
# ===========================================================================

class UserCreate(BaseModel):
    """Payload for POST /users — registering a new account."""

    username: str = Field(..., min_length=3, max_length=64, examples=["alice"])
    email: EmailStr = Field(..., examples=["alice@example.com"])
    password: str = Field(..., min_length=8, max_length=128, examples=["s3cur3P@ss"])
    public_key: str | None = Field(
        default=None,
        description="PEM/base64-encoded public key for end-to-end encryption.",
    )

    @field_validator("username")
    @classmethod
    def _username_chars(cls, v: str) -> str:
        if not USERNAME_RE.match(v):
            raise ValueError("Username must be 3–64 characters: letters, digits, _ . - only.")
        return v


class UserLogin(BaseModel):
    """Payload for POST /auth/login."""

    # max_length caps are purely a DoS guard: an attacker sending a 10 MB
    # password string would force the server to run Argon2id over it (64 MB RAM
    # per attempt × unbounded string length). We do NOT add min_length here —
    # short/wrong credentials should fail with "Invalid credentials", not a
    # Pydantic 422, so we don't leak which field is wrong via the error path.
    username: str = Field(..., max_length=64)
    password: str = Field(..., max_length=128)

    @field_validator("username")
    @classmethod
    def _username_chars(cls, v: str) -> str:
        if not USERNAME_RE.match(v):
            raise ValueError("Username must be 3–64 characters: letters, digits, _ . - only.")
        return v


class UserResponse(BaseModel):
    """Safe user representation returned by the API (no password hash)."""

    model_config = ConfigDict(from_attributes=True)   # replaces orm_mode in Pydantic v2

    id: int
    username: str
    email: EmailStr
    public_key: str | None
    is_active: bool
    created_at: datetime


class OnChainKeyInfo(BaseModel):
    """KeyRegistry.getKey() result for one identity, plus the DB's pointer
    to the most recent registration/rotation transaction (informational —
    the contract's event log remains authoritative)."""

    registered: bool
    version: int
    key_b64: str | None
    updated_at: int | None
    revoked: bool
    tx_hash: str | None = None


class UserPublicKeyResponse(BaseModel):
    """Minimal user record for public key discovery.

    Intentionally excludes email and all other PII — this schema is used by
    unauthenticated endpoints (GET /users, GET /users/{username}) whose sole
    purpose is to let a sender look up a recipient's HPKE public key.
    Returning email from an endpoint that requires no authentication would
    allow any anonymous caller to harvest the full user list with emails.
    """

    model_config = ConfigDict(from_attributes=True)

    id: int
    username: str
    public_key: str | None

    # Populated only when the caller passes ?onchain=1 — a live KeyRegistry
    # read, not a DB lookup, so a client can catch a live discrepancy
    # between what the server says and what the chain says. None when not
    # requested; also None (with onchain_error set) if the RPC call fails —
    # this endpoint never fails the whole response over a chain read.
    onchain: OnChainKeyInfo | None = None
    onchain_error: str | None = None


class PublicKeyUpload(BaseModel):
    """Body for POST /users/keys — upload or replace the caller's HPKE public key.

    The public key is the X25519 static public key generated by
    ``generate_keypair()``.  It is stored in ``users.public_key`` and
    returned by the key-discovery endpoints so other users can encrypt
    messages to this user with HPKE Mode_Auth.
    """

    # The raw 32-byte X25519 public key, base64-encoded.
    # Standard base64 of 32 bytes is exactly 44 characters (including padding).
    # URL-safe base64 is also accepted (base64.b64decode handles both when
    # validate=True is not strict about the alphabet, but we use standard
    # base64 throughout this project for consistency).
    public_key: str = Field(
        ...,
        description=(
            "Base64-encoded 32-byte X25519 public key produced by "
            "generate_keypair().  Must decode to exactly 32 bytes."
        ),
    )

    @field_validator("public_key")
    @classmethod
    def _must_decode_to_32_bytes(cls, v: str) -> str:
        # Step 1: valid base64 encoding
        try:
            raw = base64.b64decode(v, validate=True)
        except Exception:
            raise ValueError("public_key must be valid base64.")
        # Step 2: correct length for an X25519 key (HPKE_KEY_SIZE = 32)
        if len(raw) != 32:
            raise ValueError(
                f"public_key must decode to exactly 32 bytes (X25519 / HPKE); "
                f"got {len(raw)}."
            )
        return v


# ===========================================================================
# Auth / token schemas
# ===========================================================================

class Token(BaseModel):
    """JWT token pair returned after successful login."""

    access_token: str
    refresh_token: str | None = None
    token_type: str = "bearer"


class TokenData(BaseModel):
    """Claims extracted from a decoded JWT access token."""

    user_id: int | None = None
    username: str | None = None


# ===========================================================================
# Generic response wrappers
# ===========================================================================

class DetailResponse(BaseModel):
    """Generic success detail envelope."""

    detail: str


# ===========================================================================
# Auth operation schemas
# ===========================================================================

class LogoutRequest(BaseModel):
    """Body for POST /auth/logout — identifies which session to invalidate."""

    # The raw opaque refresh token returned at login.  The server hashes it
    # (SHA-256) and looks up the matching row in the sessions table.
    # Requiring it here ensures logout is tied to a specific device/session
    # rather than blindly wiping all sessions.
    refresh_token: str = Field(
        ...,
        min_length=1,
        description="The opaque refresh token issued at login.",
    )


class PasswordChange(BaseModel):
    """Body for PUT /auth/password — change the authenticated user's password."""

    # We verify old_password before accepting the change to prevent account
    # takeover on an unattended screen.  max_length prevents DoS via the
    # Argon2id verify call; we deliberately skip min_length so the error is
    # "Current password is incorrect" rather than a Pydantic 422.
    old_password: str = Field(
        ...,
        max_length=128,
        description="The user's current password (required for verification).",
    )

    # New password enforces the same policy as registration: 8–128 chars.
    new_password: str = Field(
        ...,
        min_length=8,
        max_length=128,
        description="The desired new password (min 8, max 128 characters).",
    )


# ===========================================================================
# File operation schemas
# ===========================================================================

# ---------------------------------------------------------------------------
# Upload size cap.
#
# Uploads are JSON with base64 payloads (deliberate simplicity trade-off;
# limits documented in docs/crypto-design.md §8.6).  The cap below allows
# ~8 MiB of plaintext:
#
#   ciphertext bytes = plaintext + 16 (GCM tag) = 8 MiB + 16 B
#   base64 chars     = 4 * ceil(bytes / 3)      ≈ 11 185 000
#
# Rounded up slightly for encoding slack.  A second, coarser limit on the
# whole request body (MAX_REQUEST_BODY_BYTES in main.py) rejects oversize
# requests before JSON parsing.
# ---------------------------------------------------------------------------
MAX_CIPHERTEXT_B64_LEN: int = 11_500_000


class FileUpload(BaseModel):
    """Body for POST /files/upload — upload an encrypted file for a recipient."""

    recipient_username: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Username of the intended recipient.",
    )

    # ── File metadata (optional, advisory) ────────────────────────────────
    # Stored verbatim; visible to the server (see docs/crypto-design.md §8.5).
    filename: str | None = Field(
        default=None,
        max_length=255,
        description="Original filename, for display and download naming.",
    )
    content_type: str | None = Field(
        default=None,
        max_length=127,
        description="MIME type of the plaintext (advisory; server never verifies).",
    )
    size_bytes: int | None = Field(
        default=None,
        ge=0,
        description="Plaintext size in bytes, as reported by the client.",
    )

    # The ciphertext is whatever the client's AES-256-GCM encrypt() call
    # produced — the raw encrypted bytes, base64-encoded.  The server stores
    # this opaquely; it never decrypts it.
    ciphertext: str = Field(
        ...,
        description="Base64-encoded AES-256-GCM ciphertext (without the nonce).",
    )

    # The nonce is stored separately so the download response can return it
    # as a named field without requiring the client to know the storage layout.
    # Must decode to exactly 12 bytes (96-bit GCM nonce).
    nonce: str = Field(
        ...,
        description="Base64-encoded 12-byte (96-bit) AES-256-GCM nonce.",
    )

    # Canonical AAD the client bound into the AEAD:
    #   "smx:v1:sender={sender_username}:recipient={recipient_username}:filename={filename}"
    # Optional; when present the server cross-checks it against the canonical
    # form built from this request (400 on mismatch) to catch client-side
    # construction bugs at upload time.  The server cannot verify the actual
    # AEAD binding — that check is the recipient's tag verification.
    associated_data: str | None = Field(
        default=None,
        description=(
            "Canonical AAD string bound into the AEAD by the client. "
            "Validated against the canonical form when present; see "
            "backend.crypto.build_file_aad and docs/crypto-design.md §7."
        ),
    )

    # HPKE encapsulated key: the 32-byte ephemeral X25519 public key produced
    # at encrypt time.  Not a wrapped symmetric key — the content key is
    # re-derived by the recipient via the HPKE key schedule and never stored
    # or transmitted in any form.
    encrypted_key: str | None = Field(
        default=None,
        description=(
            "Base64-encoded 32-byte HPKE encapsulated key (ephemeral X25519 "
            "public key)."
        ),
    )

    subject: str | None = Field(
        default=None,
        max_length=512,
        description="Optional subject line (may itself be client-side encrypted).",
    )

    @field_validator("nonce")
    @classmethod
    def _nonce_must_decode_to_12_bytes(cls, v: str) -> str:
        try:
            raw = base64.b64decode(v, validate=True)
        except Exception:
            raise ValueError("nonce must be valid base64.")
        if len(raw) != 12:
            raise ValueError(
                f"nonce must decode to exactly 12 bytes (AES-256-GCM); got {len(raw)}."
            )
        return v

    @field_validator("ciphertext")
    @classmethod
    def _ciphertext_size_and_tag(cls, v: str) -> str:
        # Length check FIRST — before base64-decoding — so an oversize upload
        # is rejected without materialising a second multi-MB buffer.
        if len(v) > MAX_CIPHERTEXT_B64_LEN:
            raise ValueError(
                f"ciphertext exceeds the upload limit "
                f"({MAX_CIPHERTEXT_B64_LEN} base64 chars ≈ 8 MiB plaintext)."
            )
        try:
            raw = base64.b64decode(v, validate=True)
        except Exception:
            raise ValueError("ciphertext must be valid base64.")
        # AES-256-GCM appends a 16-byte authentication tag; even an empty
        # plaintext produces exactly 16 bytes of output.
        if len(raw) < 16:
            raise ValueError(
                "ciphertext is too short to contain a valid GCM authentication tag "
                "(minimum 16 bytes)."
            )
        return v


class ShareRequest(BaseModel):
    """Body for POST /files/{id}/share — share a file with a new recipient."""

    recipient_username: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Username of the user to share the file with.",
    )

    # Re-encryption payload (preferred path).
    # The sharer decrypts the original file on their device, then re-encrypts
    # the plaintext specifically for the new recipient.  When all three fields
    # are present the backend creates a brand-new file row so the new
    # recipient can actually decrypt it.
    new_ciphertext: str | None = Field(
        default=None,
        description="Re-encrypted ciphertext (base64, without nonce prepended).",
    )
    new_nonce: str | None = Field(
        default=None,
        description="Nonce for the re-encrypted ciphertext (base64, 12 bytes).",
    )
    new_encrypted_key: str | None = Field(
        default=None,
        description="HPKE encapsulated key for the new recipient (base64, 32 bytes).",
    )

    # Legacy field kept for backward compatibility.
    encrypted_key: str | None = Field(
        default=None,
        description="Deprecated: wrapped key for shared-access forwarding.",
    )

    @field_validator("new_ciphertext")
    @classmethod
    def _new_ciphertext_within_cap(cls, v: str | None) -> str | None:
        # Same upload cap as FileUpload.ciphertext — a share re-encrypts the
        # whole file, so it must obey the same size limit.
        if v is not None and len(v) > MAX_CIPHERTEXT_B64_LEN:
            raise ValueError(
                f"new_ciphertext exceeds the upload limit "
                f"({MAX_CIPHERTEXT_B64_LEN} base64 chars ≈ 8 MiB plaintext)."
            )
        return v


class RevokeRequest(BaseModel):
    """Body for POST /files/{id}/revoke — revoke file access."""

    # If provided, revoke only this recipient's access (delete their
    # file_access row).  If omitted, revoke for all recipients.
    recipient_username: str | None = Field(
        default=None,
        description=(
            "Target recipient username. If omitted, access is revoked for all "
            "recipients (every access row is removed)."
        ),
    )


class FileListItem(BaseModel):
    """One summary item in a shared-with-me or owned-files listing.

    Does NOT include the ciphertext — that is only returned by the download
    endpoint.  This keeps the listing lightweight and prevents the server
    from accidentally returning large encrypted blobs in bulk responses.
    """

    id: int
    owner_id: int | None
    owner_username: str | None
    recipient_username: str | None = None   # populated for owned listings; None for shared
    subject: str | None
    filename: str | None = None
    content_type: str | None = None
    size_bytes: int | None = None
    is_read: bool
    is_deleted: bool
    is_forwarded: bool | None = None        # True for files created by the share endpoint
    created_at: datetime


class ReceiptInfo(BaseModel):
    """MessageReceipt status for one file, as recorded in the local DB."""

    posted: bool
    tx_hash: str | None = None


class FileDownloadResponse(BaseModel):
    """Full encrypted payload returned by GET /files/{id}/download.

    Contains everything the recipient needs to decrypt the file:
      - ciphertext  — the stored blob (nonce prepended, base64)
      - nonce       — extracted from the blob for convenience
      - associated_data — the canonical context string (informational)
      - encrypted_key   — the recipient's HPKE encapsulated key
    """

    id: int
    owner_id: int | None
    owner_username: str | None

    # The combined stored blob: base64(nonce_bytes ‖ ciphertext_with_tag).
    # The first 12 decoded bytes are the nonce; the rest is the ciphertext.
    ciphertext: str

    # Convenience field: the nonce extracted from the first 12 bytes of
    # the decoded ciphertext blob, re-encoded as base64.
    nonce: str

    # Canonical context string rebuilt by the server from stored metadata:
    #   "smx:v1:sender={username}:recipient={username}:filename={filename}"
    # Informational for display/debugging only — clients MUST rebuild the AAD
    # locally from owner_username/filename and their own username rather than
    # trust this value, since a compromised server could return a string
    # matching relabelled metadata (see docs/crypto-design.md §7).
    associated_data: str

    # The recipient's copy of the HPKE encapsulated key (ephemeral public
    # key).  Run decapsulation with your private key and the sender's public
    # key to derive the content key and decrypt the ciphertext.
    encrypted_key: str | None

    subject: str | None
    filename: str | None = None
    content_type: str | None = None
    size_bytes: int | None = None
    integrity_hash: str | None
    is_read: bool
    created_at: datetime

    # MessageReceipt status — read from the DB column (files.receipt_tx_hash),
    # not a live chain call: this is informational evidence, not a security
    # gate, so a fail-open "pending" read here is fine (see
    # docs/crypto-design.md §8.11). None if no receipt has been posted yet.
    receipt: ReceiptInfo | None = None
