"""
schemas.py — Pydantic v2 request / response models.

Keeps API contracts separate from database models.
"""

import base64
from datetime import datetime
from pydantic import BaseModel, EmailStr, Field, ConfigDict, field_validator


# ===========================================================================
# User schemas
# ===========================================================================

class UserCreate(BaseModel):
    """Payload for POST /users — registering a new account."""

    username: str = Field(..., min_length=3, max_length=64, examples=["alice"])
    email: EmailStr = Field(..., examples=["alice@example.com"])
    password: str = Field(..., min_length=8, max_length=128, examples=["s3cur3P@ss"])
    public_key: str | None = Field(
        default=None,
        description="PEM/base64-encoded public key for end-to-end encryption.",
    )


class UserLogin(BaseModel):
    """Payload for POST /auth/login."""

    # max_length caps are purely a DoS guard: an attacker sending a 10 MB
    # password string would force the server to run Argon2id over it (64 MB RAM
    # per attempt × unbounded string length). We do NOT add min_length here —
    # short/wrong credentials should fail with "Invalid credentials", not a
    # Pydantic 422, so we don't leak which field is wrong via the error path.
    username: str = Field(..., max_length=64)
    password: str = Field(..., max_length=128)


class UserResponse(BaseModel):
    """Safe user representation returned by the API (no password hash)."""

    model_config = ConfigDict(from_attributes=True)   # replaces orm_mode in Pydantic v2

    id: int
    username: str
    email: EmailStr
    public_key: str | None
    is_active: bool
    created_at: datetime


class UserPublicKeyResponse(BaseModel):
    """Minimal user record for public key discovery.

    Intentionally excludes email and all other PII — this schema is used by
    unauthenticated endpoints (GET /users, GET /users/{username}) whose sole
    purpose is to let a sender look up a recipient's HPKE public key.
    Returning email from an endpoint that requires no authentication would
    allow any anonymous caller to harvest the full user list with emails.
    """

    model_config = ConfigDict(from_attributes=True)

    id: int
    username: str
    public_key: str | None


class PublicKeyUpload(BaseModel):
    """Body for POST /users/keys — upload or replace the caller's HPKE public key.

    The public key is the X25519 static public key generated by
    ``generate_keypair()``.  It is stored in ``users.public_key`` and
    returned by the key-discovery endpoints so other users can encrypt
    messages to this user with HPKE Mode_Auth.
    """

    # The raw 32-byte X25519 public key, base64-encoded.
    # Standard base64 of 32 bytes is exactly 44 characters (including padding).
    # URL-safe base64 is also accepted (base64.b64decode handles both when
    # validate=True is not strict about the alphabet, but we use standard
    # base64 throughout this project for consistency).
    public_key: str = Field(
        ...,
        description=(
            "Base64-encoded 32-byte X25519 public key produced by "
            "generate_keypair().  Must decode to exactly 32 bytes."
        ),
    )

    @field_validator("public_key")
    @classmethod
    def _must_decode_to_32_bytes(cls, v: str) -> str:
        # Step 1: valid base64 encoding
        try:
            raw = base64.b64decode(v, validate=True)
        except Exception:
            raise ValueError("public_key must be valid base64.")
        # Step 2: correct length for an X25519 key (HPKE_KEY_SIZE = 32)
        if len(raw) != 32:
            raise ValueError(
                f"public_key must decode to exactly 32 bytes (X25519 / HPKE); "
                f"got {len(raw)}."
            )
        return v


# ===========================================================================
# Message schemas
# ===========================================================================

class MessageCreate(BaseModel):
    """Payload for POST /messages — sending an encrypted message."""

    recipient_ids: list[int] = Field(
        ...,
        min_length=1,
        description="One or more user IDs that should receive this message.",
    )
    ciphertext: str = Field(
        ...,
        description="Base64-encoded encrypted message payload.",
    )
    subject: str | None = Field(
        default=None,
        max_length=512,
        description="Optional (possibly encrypted) subject line.",
    )
    encrypted_keys: dict[int, str] = Field(
        default_factory=dict,
        description=(
            "Mapping of recipient_id → wrapped symmetric key "
            "(encrypted with that recipient's public key)."
        ),
    )
    integrity_hash: str | None = Field(
        default=None,
        description="HMAC / SHA-256 integrity tag for tamper detection.",
    )


class MessageResponse(BaseModel):
    """Message representation returned by the API."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    sender_id: int | None
    ciphertext: str
    subject: str | None
    integrity_hash: str | None
    is_deleted: bool
    created_at: datetime


# ===========================================================================
# Auth / token schemas
# ===========================================================================

class Token(BaseModel):
    """JWT token pair returned after successful login."""

    access_token: str
    refresh_token: str | None = None
    token_type: str = "bearer"


class TokenData(BaseModel):
    """Claims extracted from a decoded JWT access token."""

    user_id: int | None = None
    username: str | None = None


# ===========================================================================
# Generic response wrappers
# ===========================================================================

class MessageOut(BaseModel):
    """Generic success message envelope."""

    detail: str


# ===========================================================================
# Auth operation schemas
# ===========================================================================

class LogoutRequest(BaseModel):
    """Body for POST /auth/logout — identifies which session to invalidate."""

    # The raw opaque refresh token returned at login.  The server hashes it
    # (SHA-256) and looks up the matching row in the sessions table.
    # Requiring it here ensures logout is tied to a specific device/session
    # rather than blindly wiping all sessions.
    refresh_token: str = Field(
        ...,
        min_length=1,
        description="The opaque refresh token issued at login.",
    )


class PasswordChange(BaseModel):
    """Body for PUT /auth/password — change the authenticated user's password."""

    # We verify old_password before accepting the change to prevent account
    # takeover on an unattended screen.  max_length prevents DoS via the
    # Argon2id verify call; we deliberately skip min_length so the error is
    # "Current password is incorrect" rather than a Pydantic 422.
    old_password: str = Field(
        ...,
        max_length=128,
        description="The user's current password (required for verification).",
    )

    # New password enforces the same policy as registration: 8–128 chars.
    new_password: str = Field(
        ...,
        min_length=8,
        max_length=128,
        description="The desired new password (min 8, max 128 characters).",
    )


# ===========================================================================
# Message operation schemas
# ===========================================================================

class MessageSend(BaseModel):
    """Body for POST /messages/send — send an encrypted message."""

    recipient_username: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Username of the intended recipient.",
    )

    # The ciphertext is whatever the client's AES-256-GCM encrypt() call
    # produced — the raw encrypted bytes, base64-encoded.  The server stores
    # this opaquely; it never decrypts it.
    ciphertext: str = Field(
        ...,
        description="Base64-encoded AES-256-GCM ciphertext (without the nonce).",
    )

    # The nonce is stored separately so the download response can return it
    # as a named field without requiring the client to know the storage layout.
    # Must decode to exactly 12 bytes (96-bit GCM nonce).
    nonce: str = Field(
        ...,
        description="Base64-encoded 12-byte (96-bit) AES-256-GCM nonce.",
    )

    # The server enforces the canonical AAD convention
    # "v1:sender={id}:recipient={id}:msg={id}" and returns it in the download
    # response.  This field is accepted from the client for documentation and
    # may be used in future for client-side verification, but the server
    # always computes the authoritative value from message metadata.
    associated_data: str | None = Field(
        default=None,
        description=(
            "Associated data used by the client for AEAD. The server computes "
            "the canonical AAD from message metadata; this field is informational."
        ),
    )

    # Wrapped (public-key-encrypted) copy of the message's symmetric key,
    # so the recipient can unwrap it with their private key and then decrypt
    # the ciphertext.  The server never sees the raw symmetric key.
    encrypted_key: str | None = Field(
        default=None,
        description=(
            "Base64-encoded message symmetric key encrypted with the "
            "recipient's public key."
        ),
    )

    subject: str | None = Field(
        default=None,
        max_length=512,
        description="Optional subject line (may itself be client-side encrypted).",
    )

    @field_validator("nonce")
    @classmethod
    def _nonce_must_decode_to_12_bytes(cls, v: str) -> str:
        try:
            raw = base64.b64decode(v, validate=True)
        except Exception:
            raise ValueError("nonce must be valid base64.")
        if len(raw) != 12:
            raise ValueError(
                f"nonce must decode to exactly 12 bytes (AES-256-GCM); got {len(raw)}."
            )
        return v

    @field_validator("ciphertext")
    @classmethod
    def _ciphertext_must_contain_tag(cls, v: str) -> str:
        try:
            raw = base64.b64decode(v, validate=True)
        except Exception:
            raise ValueError("ciphertext must be valid base64.")
        # AES-256-GCM appends a 16-byte authentication tag; even an empty
        # plaintext produces exactly 16 bytes of output.
        if len(raw) < 16:
            raise ValueError(
                "ciphertext is too short to contain a valid GCM authentication tag "
                "(minimum 16 bytes)."
            )
        return v


class ForwardRequest(BaseModel):
    """Body for POST /messages/{id}/forward."""

    recipient_username: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Username of the user to forward the message to.",
    )

    # The forwarder must decrypt the message_key with their own private key,
    # re-encrypt it with the new recipient's public key, and supply it here.
    # Without this, the new recipient cannot decrypt the ciphertext.
    encrypted_key: str | None = Field(
        default=None,
        description=(
            "Message symmetric key re-wrapped with the new recipient's public key."
        ),
    )


class RevokeRequest(BaseModel):
    """Body for POST /messages/{id}/revoke — revoke message access."""

    # If provided, revoke only this recipient's access (delete their
    # message_access row).  If omitted, revoke for all recipients by
    # soft-deleting the message entirely (is_deleted = True).
    recipient_username: str | None = Field(
        default=None,
        description=(
            "Target recipient username. If omitted, access is revoked for all "
            "recipients (full soft-delete)."
        ),
    )


class MessageListItem(BaseModel):
    """One summary item in an inbox or sent-messages listing.

    Does NOT include the ciphertext — that is only returned by the download
    endpoint.  This keeps the listing lightweight and prevents the server
    from accidentally returning large encrypted blobs in bulk responses.
    """

    id: int
    sender_id: int | None
    sender_username: str | None
    recipient_username: str | None = None   # populated for sent listings; None for inbox
    subject: str | None
    is_read: bool
    is_deleted: bool
    created_at: datetime


class MessageDownloadResponse(BaseModel):
    """Full message payload returned by GET /messages/{id}/download.

    Contains everything the recipient needs to decrypt the message:
      - ciphertext  — the stored blob (nonce prepended, base64)
      - nonce       — extracted from the blob for convenience
      - associated_data — the canonical AAD string; pass this to decrypt()
      - encrypted_key   — the recipient's wrapped symmetric key
    """

    id: int
    sender_id: int | None
    sender_username: str | None

    # The combined stored blob: base64(nonce_bytes ‖ ciphertext_with_tag).
    # The first 12 decoded bytes are the nonce; the rest is the ciphertext.
    ciphertext: str

    # Convenience field: the nonce extracted from the first 12 bytes of
    # the decoded ciphertext blob, re-encoded as base64.
    nonce: str

    # Canonical AAD string computed by the server:
    #   "v1:sender={sender_id}:recipient={recipient_id}:msg={message_id}"
    # Pass this verbatim as associated_data to your AEAD decrypt() call.
    associated_data: str

    # The recipient's copy of the wrapped symmetric key.  Decrypt with your
    # private key to recover the message_key, then use message_key + nonce +
    # associated_data to decrypt the ciphertext.
    encrypted_key: str | None

    subject: str | None
    integrity_hash: str | None
    is_read: bool
    created_at: datetime
